/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#4edea3",
        "surface-dim": "#131313",
        "on-secondary-fixed-variant": "#474746",
        "surface-variant": "#353534",
        "on-surface-variant": "#c4c5d9",
        "tertiary-fixed": "#6ffbbe",
        "primary-fixed": "#dde1ff",
        "on-primary-fixed-variant": "#0035bd",
        "tertiary-container": "#007e56",
        "surface-tint": "#b8c3ff",
        "on-primary-fixed": "#001355",
        "on-tertiary": "#003824",
        "on-secondary-container": "#b7b5b4",
        "surface": "#131313",
        "on-error": "#690005",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed": "#002113",
        "inverse-on-surface": "#313030",
        "tertiary-fixed-dim": "#4edea3",
        "surface-container-low": "#1c1b1b",
        "primary-container": "#2f5cff",
        "secondary-fixed-dim": "#c8c6c5",
        "on-tertiary-fixed-variant": "#005236",
        "on-surface": "#e5e2e1",
        "on-primary": "#002388",
        "secondary": "#c8c6c5",
        "inverse-primary": "#124aef",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary": "#303030",
        "on-primary-container": "#f0f0ff",
        "on-tertiary-container": "#c5ffde",
        "primary-fixed-dim": "#b8c3ff",
        "error-container": "#93000a",
        "primary": "#b8c3ff",
        "outline": "#8e90a2",
        "secondary-fixed": "#e4e2e1",
        "secondary-container": "#474746",
        "on-error-container": "#ffdad6",
        "surface-container-highest": "#353534",
        "outline-variant": "#434656",
        "error": "#ffb4ab",
        "on-background": "#e5e2e1",
        "background": "#131313",
        "on-secondary-fixed": "#1b1c1c",
        "surface-container-high": "#2a2a2a",
        "surface-container": "#201f1f",
        "inverse-surface": "#e5e2e1",
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
