/** @type {import('tailwindcss').Config} */
const withOpacity = (variable) => `rgb(var(${variable}) / <alpha-value>)`

export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": withOpacity("--color-tertiary"),
        "surface-dim": withOpacity("--color-surface-dim"),
        "on-secondary-fixed-variant": withOpacity("--color-on-secondary-fixed-variant"),
        "surface-variant": withOpacity("--color-surface-variant"),
        "on-surface-variant": withOpacity("--color-on-surface-variant"),
        "tertiary-fixed": withOpacity("--color-tertiary-fixed"),
        "primary-fixed": withOpacity("--color-primary-fixed"),
        "on-primary-fixed-variant": withOpacity("--color-on-primary-fixed-variant"),
        "tertiary-container": withOpacity("--color-tertiary-container"),
        "surface-tint": withOpacity("--color-surface-tint"),
        "on-primary-fixed": withOpacity("--color-on-primary-fixed"),
        "on-tertiary": withOpacity("--color-on-tertiary"),
        "on-secondary-container": withOpacity("--color-on-secondary-container"),
        "surface": withOpacity("--color-surface"),
        "on-error": withOpacity("--color-on-error"),
        "surface-bright": withOpacity("--color-surface-bright"),
        "on-tertiary-fixed": withOpacity("--color-on-tertiary-fixed"),
        "inverse-on-surface": withOpacity("--color-inverse-on-surface"),
        "tertiary-fixed-dim": withOpacity("--color-tertiary-fixed-dim"),
        "surface-container-low": withOpacity("--color-surface-container-low"),
        "primary-container": withOpacity("--color-primary-container"),
        "secondary-fixed-dim": withOpacity("--color-secondary-fixed-dim"),
        "on-tertiary-fixed-variant": withOpacity("--color-on-tertiary-fixed-variant"),
        "on-surface": withOpacity("--color-on-surface"),
        "on-primary": withOpacity("--color-on-primary"),
        "secondary": withOpacity("--color-secondary"),
        "inverse-primary": withOpacity("--color-inverse-primary"),
        "surface-container-lowest": withOpacity("--color-surface-container-lowest"),
        "on-secondary": withOpacity("--color-on-secondary"),
        "on-primary-container": withOpacity("--color-on-primary-container"),
        "on-tertiary-container": withOpacity("--color-on-tertiary-container"),
        "primary-fixed-dim": withOpacity("--color-primary-fixed-dim"),
        "error-container": withOpacity("--color-error-container"),
        "primary": withOpacity("--color-primary"),
        "outline": withOpacity("--color-outline"),
        "secondary-fixed": withOpacity("--color-secondary-fixed"),
        "secondary-container": withOpacity("--color-secondary-container"),
        "on-error-container": withOpacity("--color-on-error-container"),
        "surface-container-highest": withOpacity("--color-surface-container-highest"),
        "outline-variant": withOpacity("--color-outline-variant"),
        "error": withOpacity("--color-error"),
        "on-background": withOpacity("--color-on-background"),
        "background": withOpacity("--color-background"),
        "on-secondary-fixed": withOpacity("--color-on-secondary-fixed"),
        "surface-container-high": withOpacity("--color-surface-container-high"),
        "surface-container": withOpacity("--color-surface-container"),
        "inverse-surface": withOpacity("--color-inverse-surface"),
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
